name: 'Lint Python Projects and Sync with AWS codecommit'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: ./
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        python3 -m pylint --rcfile=.pylintrc ${{ env.workdir }}*.py

  to_codecommit:                                        # <-- different jobs are executed in parallel.
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: pushes to codecommit
      env:
        CODECOMMIT_URL: ${{ secrets.CODECOMMIT_URL }}
        HOST_KEY: ${{ secrets.HOST_KEY }}
        SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      shell: bash
      run: |
        dir=$PWD
        mkdir -p ~/.ssh && cd ~/.ssh && echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
        echo "$SSH_CONFIG" > config && chmod 600 config
        ssh-keyscan -t rsa git-codecommit.us-west-2.amazonaws.com >> known_hosts && chmod 600 known_hosts && cd $dir
        git remote add codecommit "$CODECOMMIT_URL"
        git push codecommit main --force
        sudo chmod -R 777 $dir
